Created the footer
citi-onboarding/colisio pull request #2
Opened 2023-05-31 21:27 UTC by marcos-gma

## What I did

- Created the footer

## How to test

1. Open the terminal and go to the folder of this project

2. In terminal:
   `git checkout develop`
   `git pull`
   `git checkout <branch name>`
   `git pull origin <branch name>`
   `yarn install`
   `yarn start`

1. In your browser go to http://localhost:port

1. Check if the component looks just like the mockup in different screen sizes 

1. Read the changed files section on GitHub 

1. Test the things that you think are worth testing, even the ones that are not in this description

2023-05-31 21:41 UTC, damattag requested changes

2023-05-31 21:41 UTC, damattag commented on client/src/pages/footer/styles.ts
> +`;
não é interessante que usemos o position absolute, nesse caso o melhor é retira-lo, quando colocamos um componente abaixo do outro no app eles serão renderizados exatamente nessa ordem, então se o footer for o último ele ja estará embaixo.

2023-05-31 21:41 UTC, damattag commented on client/src/pages/footer/styles.ts
> +    left: 186px;
aqui também, no geral, não usamos o position absolute, recomendo que use e tire proveito do display flex.

2023-05-31 21:41 UTC, damattag commented on client/src/pages/footer/styles.ts
> +`;
![image](https://github.com/citi-onboarding/colisio/assets/92034541/fe5a7b43-6e71-46a2-ba19-cd67f93d650d)
no geral, está bom, precisa só ver a questão de ter usado o position absolute nos elementos, ele não é bom para a responsividade e deve ser usado somente em casos mais específicos, recomendo que use o display flex que será de grande ajuda. A imagem representa o que acontece ao usarmos o position dessa forma, mas fora isso, tá bom, parabens.

2023-06-07 16:12 UTC, damattag requested changes
![image](https://github.com/citi-onboarding/colisio/assets/92034541/9bc81f06-83ab-4904-81d2-cef9abea3bc9)
as informações no footer estão todas desalinhadas com os títulos

2023-06-07 16:12 UTC, damattag commented on client/src/pages/footer/styles.ts
> +    width: 48px;
não é uma boa prática usar tantos valores negativos assim

2023-06-08 17:53 UTC, marcos-gma commented on client/src/pages/footer/styles.ts
> +    width: 48px;
Tava alinhado para mim aqui, vou checar qual foi o problema. Sobre os negativos vou tentar tirar o máximo que der.

2023-06-10 13:37 UTC, damattag approved these changes

2023-06-10 13:48 UTC, damattag requested changes, later dismissed
a

2023-06-10 14:06 UTC, joca113 approved these changes

2023-06-14 16:17 UTC, merged